server:
  port: 8080

spring:
  application:
    name: liquibase
  datasource:
    url: jdbc:h2:mem:farmaciala-online
    username: root
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


